name: Build Chain

on: [pull_request]
jobs:
  build-chain:
    runs-on: ubuntu-latest
    steps:
      - name: "Set up JDK"
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: "Run build-chain"
        id: build-chain
        uses: kiegroup/github-action-build-chain@v2.6.24
        with:
          definition-file: https://raw.githubusercontent.com/waggle-sensor/bc-test-build-chain/main/definitions.yml
          logger-level: debug
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
